<?php
return Array (
    '0' => Array (
        'LID' => 'ru',
        'NAME' => 'Includer Content',
        'SECTION_NAME' => '',
        'ELEMENT_NAME' => '',
        'ID' => 'bit_includer',
        'SECTIONS' => 'Y',
        'SORT' => '500',
        'LANG' => Array (
            LANGUAGE_ID => Array (
                'NAME' => 'Includer Content',
                'SECTION_NAME' => '',
                'ELEMENT_NAME' => '',
            ),
        ),
        'IBLOCKS' => Array (
            '0' => Array (
                'CODE' => 'bit_includer_content',
                'NAME' => 'Слайдер',
                'ACTIVE' => 'Y',
                'SORT' => '500',
                'LIST_PAGE_URL' => '#SITE_DIR#/bit_includer/index.php?ID=#IBLOCK_ID#',
                'DETAIL_PAGE_URL' => '#SITE_DIR#/bit_includer/detail.php?ID=#ELEMENT_ID#',
                'SECTION_PAGE_URL' => '#SITE_DIR#/bit_includer/list.php?SECTION_ID=#SECTION_ID#',
                'INDEX_ELEMENT' => 'Y',
                'INDEX_SECTION' => 'Y',
                'WORKFLOW' => 'N',
                'BIZPROC' => 'N',
                'SECTION_CHOOSER' => 'L',
                'LIST_MODE' => '',
                'RIGHTS_MODE' => 'S',
                'VERSION' => '1',
                'EDIT_FILE_BEFORE' => '',
                'EDIT_FILE_AFTER' => '',
                'SECTIONS_NAME' => 'Разделы',
                'SECTION_NAME' => 'Раздел',
                'ELEMENTS_NAME' => 'Элементы',
                'ELEMENT_NAME' => 'Элемент',
                'SITE_ID' => Array (
                    '0' => $sSiteId,
                ),
                'SECTIONS' => Array (
                    '0' => Array (
                        'IBLOCK_SECTION_ID' => '',
                        'ACTIVE' => 'Y',
                        'GLOBAL_ACTIVE' => 'Y',
                        'SORT' => '500',
                        'NAME' => 'Демо 1',
                        'PICTURE' => '',
                        'LEFT_MARGIN' => '1',
                        'RIGHT_MARGIN' => '2',
                        'DEPTH_LEVEL' => '1',
                        'DESCRIPTION' => '',
                        'DESCRIPTION_TYPE' => 'text',
                        'SEARCHABLE_CONTENT' => 'ДЕМО 1
',
                        'CODE' => 'demo-1',
                        'XML_ID' => '',
                        'DETAIL_PICTURE' => '',
                        'EXTERNAL_ID' => '',
                        'ELEMENTS' => Array (
                            '0' => Array (
                                'CODE' => 'poezda',
                                'EXTERNAL_ID' => '9',
                                'NAME' => 'Поезда',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti.',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '9',
                                    'TIMESTAMP_X' => '06.01.2015 02:08:59',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '768',
                                    'WIDTH' => '1024',
                                    'FILE_SIZE' => '472843',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/d89',
                                    'FILE_NAME' => '4591037078_a05d92ca04_b.jpg',
                                    'ORIGINAL_NAME' => '4591037078_a05d92ca04_b.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/d89/4591037078_a05d92ca04_b.jpg',
                                    'NEW_SRC' => '9.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                            '1' => Array (
                                'CODE' => 'ulitka',
                                'EXTERNAL_ID' => '10',
                                'NAME' => 'Улитка',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '10',
                                    'TIMESTAMP_X' => '06.01.2015 02:09:10',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1365',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '200126',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/3c6',
                                    'FILE_NAME' => '14190877956_013060813f_k.jpg',
                                    'ORIGINAL_NAME' => '14190877956_013060813f_k.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/3c6/14190877956_013060813f_k.jpg',
                                    'NEW_SRC' => '10.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                            '2' => Array (
                                'CODE' => 'tsvetok',
                                'EXTERNAL_ID' => '11',
                                'NAME' => 'Цветок',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '11',
                                    'TIMESTAMP_X' => '06.01.2015 02:09:35',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1441',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '2039798',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/00d',
                                    'FILE_NAME' => '14328551411_505a721b10_k.jpg',
                                    'ORIGINAL_NAME' => '14328551411_505a721b10_k.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/00d/14328551411_505a721b10_k.jpg',
                                    'NEW_SRC' => '11.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                        ),
                    ),
                    '1' => Array (
                        'IBLOCK_SECTION_ID' => '',
                        'ACTIVE' => 'Y',
                        'GLOBAL_ACTIVE' => 'Y',
                        'SORT' => '500',
                        'NAME' => 'Демо 2',
                        'PICTURE' => '',
                        'LEFT_MARGIN' => '3',
                        'RIGHT_MARGIN' => '4',
                        'DEPTH_LEVEL' => '1',
                        'DESCRIPTION' => '',
                        'DESCRIPTION_TYPE' => 'text',
                        'SEARCHABLE_CONTENT' => 'ДЕМО 2
',
                        'CODE' => 'demo-2',
                        'XML_ID' => '',
                        'DETAIL_PICTURE' => '',
                        'EXTERNAL_ID' => '',
                        'ELEMENTS' => Array (
                            '0' => Array (
                                'CODE' => 'ptitsa',
                                'EXTERNAL_ID' => '12',
                                'NAME' => 'Птица',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '12',
                                    'TIMESTAMP_X' => '06.01.2015 02:09:55',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1314',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '926226',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/f18',
                                    'FILE_NAME' => '15405160939_d652269b95_k.jpg',
                                    'ORIGINAL_NAME' => '15405160939_d652269b95_k.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/f18/15405160939_d652269b95_k.jpg',
                                    'NEW_SRC' => '12.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                            '1' => Array (
                                'CODE' => 'most',
                                'EXTERNAL_ID' => '13',
                                'NAME' => 'Мост',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti.',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '13',
                                    'TIMESTAMP_X' => '06.01.2015 02:10:20',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1348',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '850725',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/b0b',
                                    'FILE_NAME' => '15429962823_6ba5a1e907_k.jpg',
                                    'ORIGINAL_NAME' => '15429962823_6ba5a1e907_k.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/b0b/15429962823_6ba5a1e907_k.jpg',
                                    'NEW_SRC' => '13.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                            '2' => Array (
                                'CODE' => 'utro',
                                'EXTERNAL_ID' => '14',
                                'NAME' => 'Утро',
                                'ACTIVE' => 'Y',
                                'DATE_ACTIVE_FROM' => '',
                                'SORT' => '500',
                                'PREVIEW_PICTURE' => '',
                                'PREVIEW_TEXT' => 'Lorem ipsum dolor sit amet, &quot;consectetur&quot; adipiscing elit. Sed at blandit mi. Morbi et odio et purus finibus ultricies. Suspendisse potenti. ',
                                'PREVIEW_TEXT_TYPE' => 'text',
                                'DETAIL_PICTURE' => Array (
                                    'ID' => '14',
                                    'TIMESTAMP_X' => '06.01.2015 02:10:33',
                                    'MODULE_ID' => 'iblock',
                                    'HEIGHT' => '1361',
                                    'WIDTH' => '2048',
                                    'FILE_SIZE' => '923891',
                                    'CONTENT_TYPE' => 'image/jpeg',
                                    'SUBDIR' => 'iblock/e8c',
                                    'FILE_NAME' => '16165013326_03619b50d9_k.jpg',
                                    'ORIGINAL_NAME' => '16165013326_03619b50d9_k.jpg',
                                    'DESCRIPTION' => '',
                                    'HANDLER_ID' => '',
                                    '~src' => '',
                                    'SRC' => '/upload/iblock/e8c/16165013326_03619b50d9_k.jpg',
                                    'NEW_SRC' => '14.jpg',
                                ),
                                'DETAIL_TEXT' => '',
                                'DETAIL_TEXT_TYPE' => 'text',
                                'TAGS' => '',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
);
?>